### PR TITLE
V4

### PR DESCRIPTION
**Pull request by nathanielksmith**
it's all happening for real

* Port to postgresql + sqlalchemy
* Completely rewrite command line interface
* Add a --verbose flag and muzzle the logging that used to happen
  unless it's present
* Support a configuration file (~/.prosaic/prosaic.conf) for
  specifying database connections and default template
* Rename some modules
* Remove some vestigial features

### CODE REVIEW

**Comment by mckern** [comment]
SQUASH SOME OF YOUR COMMITS, DAWG

**Comment by nathanielksmith** [comment]
NO I LOVE MY COMMITS

**Comment by mckern** [comment]
stare hard

**Comment by mckern** [comment]
excited swanson

**Comment by nathanielksmith** [comment]
hahaha

**Pull request merged**
